- .storybook/font.css
- .storybook/main.js
- .storybook/manager.js
- .storybook/preview-head.html
- .storybook/preview.jsx
- .storybook/theme.js
- package.json
- src/stories/Button.stories.mdx
- src/theme/list/dark.ts
- yarn.lock
> feat: storybook setup

- .storybook/preview.jsx
- src/style/style.tsx
Глобальные стили ломали прокрутку в storybook
> fix: storybook global style

- src/notifications/popup/Popup.service.ts
- src/notifications/popup/Popup.tsx
- src/notifications/popup/PopupProps.ts
> feat: simplify popup closing

- .storybook/preview.jsx
- src/components/utils/Restory.tsx
- src/stories/SquareGroupSwitcher.stories.mdx
- src/stories/SquareGroupToggle.stories.mdx
> feat: square group storybook

- src/components/molecules/SquareGroup.tsx
- src/components/molecules/SquareGroupSwitcher.tsx
- src/components/molecules/VersionPicker.tsx
- src/core/providers/types.ts
- src/stories/SquareGroupSwitcher.stories.mdx
- src/stories/VersionPicker.stories.mdx
Заверстал чётко пикер версий Minecraft
> feat: version picker

- src/core/install/populate.ts
- src/core/launch/args.ts
- src/core/utils/dedupe.ts
- src/core/utils/inheritance.ts
- src/core/version/version.ts
- src/minecraft/GameProfile.service.ts
- src/minecraft/Instance.ts
Forge и Fabric с фронта теперь грузит без проблем
> fix: version inheritance

- src/minecraft/Instance.ts
- src/notifications/upfall/Upfall.tsx
- src/screens/Main/PlaySubscreen/InstanceItem.tsx
> feat: error handling

- src/components/atoms/Button.tsx
- src/screens/Main/PlaySubscreen/InstanceItem.tsx
Отключаю кнопки на инстансе, когда устанавливается, ещё добавил статус точку, которая "горит" когда инстанс запущен
> feat: improve instance item buttons

- rust/tauri.conf.json
- src/minecraft/Instance.ts
- src/screens/Main/PlaySubscreen/InstanceItem.tsx
> feat: open in explorer

- package.json
- src/minecraft/Instance.ts
- src/screens/Main/PlaySubscreen/InstanceItem.tsx
- src/screens/Main/PlaySubscreen/PlaySubscreen.tsx
- src/user/PlayerLite.service.ts
- yarn.lock
> feat: player lite

- src/screens/Main/PlaySubscreen/PlaySubscreen.tsx
Хз из-за чего но утечка памяти
> fix: detached elements memory leak

- rust/commands/src/compat/unzip.rs
- src/core/launch/args.ts
- src/core/launch/launch.ts
- src/java/JavaRuntime.service.ts
- src/java/adoptium.ts
- src/minecraft/Instance.ts
> fix: unzip and legacy loading

- src/minecraft/Instance.ts
- src/screens/Main/JournalSubscreen/JournalSubscreen.tsx
> feat: clear logs ability

- src/core/providers/index.ts
- src/core/utils/isSnapshot.ts
> feat: reject legacy versions

- src/components/organisms/InstanceEditor.tsx
> feat: full instance deleting

- .github/workflows/publish.yml
- src/core/launch/launch.ts
- src/core/utils/dedupe.ts
- src/debug/error.ts
- src/java/JavaRuntime.service.ts
- src/minecraft/Instance.ts
- src/screens/Main/PlaySubscreen/InstanceItem.tsx
- src/screens/Main/SettingsSubscreen/SettingsSubscreen.tsx
> fix: few fixes

- src/components/molecules/VersionPicker.tsx
- src/i18n/langs/en_US.ts
- src/i18n/langs/ru_RU.ts
> feat: version filtering

- src/components/organisms/InstanceEditor.tsx
- src/components/organisms/header/WindowControl.tsx
- src/notifications/popup/Popup.tsx
> fix: prerelease fixes

- src/screens/Main/PlaySubscreen/InstanceItem.tsx
> fix: reset progress on error

- vite.config.ts
> feat: improve vite config

- rust/Cargo.lock
- rust/Cargo.toml
- rust/src/main.rs
- vite.config.ts
> feat: deeplink plugin

- package.json
- src/components/atoms/Text.tsx
- src/components/molecules/VersionPicker.tsx
- src/components/utils/Scrollbar.tsx
- src/screens/Main/JournalSubscreen/JournalSubscreen.tsx
- yarn.lock
Наконец то полоса прокрутки теперь есть
> feat: scrollbars

- package.json
- rust/tauri.conf.json
> chore: bump version to v0.2.3

- src/components/organisms/InstanceEditor.tsx
- src/native/rust/download.ts
- src/native/rust/unzip.ts
- src/native/shell/java.ts
- src/notifications/popup/popup.service.ts
- src/notifications/upfall/upfall.service.ts
> chore: switch to non secure nanoid for performance

- package.json
- src/components/molecules/VersionPicker.tsx
- src/components/organisms/InstanceEditor.tsx
- src/main.tsx
- src/minecraft/game-profile/game-profile.service.ts
- src/minecraft/game-profile/game-profile.store.ts
- yarn.lock
Добавил `react-query` для оптимизации
> feat: integrate react-query

- package.json
- rust/tauri.conf.json
- src/components/atoms/Button.tsx
- src/components/molecules/VersionPicker.tsx
- src/screens/Main/JournalSubscreen/JournalSubscreen.tsx
- src/screens/Main/PlaySubscreen/InstanceItem.tsx
> chore: prepare v0.3.0

- src/core/injector.ts
- src/core/install/install.ts
- src/core/launch/args.ts
- src/core/utils/libutils.ts
> feat: authLib injector
